spring.application.name=spring-ai
<<<<<<< HEAD

# OpenRouter
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.base-url=${OPENAI_BASE_URL}
spring.ai.openai.chat.options.model=meta-llama/llama-3-8b-instruct
spring.ai.openai.chat.completions-path=/chat/completions

# HuggingFace
huggingface.api.key=${HUGGINGFACE_API_KEY}
huggingface.api.url=${HUGGINGFACE_API_URL}

# Supabase
supabase.key=${SUPABASE_KEY}
supabase.url=${SUPABASE_URL}
supabase.bucket=images

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
=======
#spring.application.name=spring-ai
spring.ai.openai.api-key=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
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.ai.openai.chat.options.model=meta-llama/llama-3-8b-instruct
spring.ai.openai.base-url=https://openrouter.ai/api/v1
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web=DEBUG
spring.ai.openai.chat.completions-path=/chat/completions
#spring.ai.openai.chat.options.model=google/gemma-7b-it
huggingface.api.key=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
huggingface.api.url=https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell
<<<<<<< HEAD

>>>>>>> d24af22 (git add .)
=======
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndocGN3c2R0b3RxZ3FndnNqcnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU4MDk2NjksImV4cCI6MjA5MTM4NTY2OX0.E0ZZRlbw9-7NQACIS6oD2HxRfsO6_f_NOXPAvSAp2EA
supabase.url=https://whpcwsdtotqgqgvsjrqr.supabase.co
supabase.bucket=images
spring.datasource.url=jdbc:postgresql://db.whpcwsdtotqgqgvsjrqr.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Shoaib@2838
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
>>>>>>> a8bd43e (fixed lock issue)
