spring.application.name=spring-ai
spring.ai.openai.api-key=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
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.ai.openai.chat.options.model=meta-llama/llama-3-8b-instruct
spring.ai.openai.base-url=https://openrouter.ai/api/v1
logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web=DEBUG
spring.ai.openai.chat.completions-path=/chat/completions
#spring.ai.openai.chat.options.model=google/gemma-7b-it
huggingface.api.key=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
huggingface.api.url=https://router.huggingface.co/hf-inference/models/black-forest-labs/FLUX.1-schnell

