spring.application.name=spring-ai
spring.ai.open.ai.api-key=Ai-image-generatorOBC7oULEcDxqRrcHLI9m4a2hj6mPlfG3
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration